### ISSUE TITLE
[REQUEST] Add support for multiple monitors

### ISSUE THREAD

**Issue by Baegus** [ygoe/T-Clock#2]
It probably isn't possible, but I have no idea how the Windows clock is replaced, so there might be a chance for a proper multi-monitor support.

**Comment by ygoe** [comment]
What is "multi-monitor support"? There is only one taskbar on a Windows desktop. (Unless you choose display mirroring.) The clock is replaced just where Windows Explorer would put it on its own. So there's only a single location for it.

**Comment by Baegus** [comment]
I completely forgot - there is an option for multi-monitor taskbar in Windows 8, but there is no system tray on that taskbar, therefore no clock. I don't remember this being possible in Windows 7, which is probably why you're confused. It would be handy to have T-Clock in here.

**Comment by ygoe** [comment]
Umm, I'm not really so deep inside the code. I just collected some floating patches and made a build from that. So if there's not even a default clock on those additional taskbars, I fear I can't add one with this program. My Windows 8 experience is currently limited to virtual machines and some tablets in electronics stores where I don't have multiple monitors.

**Comment by White-Tiger** [comment]
It should be able to be added... but it's not an easy task ;) Basically T-Clock finds the original Clock and overtakes it... so the original Clock window is basically controlled by T-Clock from that point.. since those extra taskbars don't have a clock, T-Clock would have to create them first... (basically a new child window to the taskbar)
This should be very possible from my understanding but it's still lot of code (well I rewrite all those hooking sometime anyway, so I might consider this as well)

What do you expect the mirror clocks to do? Mirroring them should be relative simple.. but having them behave differently is again a lot of work...

**Comment by Baegus** [comment]
Ideally, it would be the same clock as the main one. It frustrates me that there's no clock on the other taskbar and since T-Clock messes with the original clock anyway, I thought it would be a nice feature to have.

**Comment by White-Tiger** [comment]
Here you go: https://github.com/White-Tiger/T-Clock/releases/tag/v2.2.0%2384-beta
Should work ;)

**Comment by Baegus** [comment]
Oh my god, thank you so much, it works like charm.
