### ISSUE TITLE
Bug: week number incorrect in Time Format

### ISSUE THREAD

**Issue by jerry1970** [ygoe/T-Clock#3]
While the popup calendar shows 2015-02-23 is week **9** (which is correct according to many sources on the web), the custom format

```
"wk" Ws Wm Ww, ddd yyyy-mm-dd hh:nn:ss
```

shows today as week **8**:

```
wk 08 08 8, ma 2015-02-23 09:07:07
```

**Comment by jerry1970** [comment]
I now see in the change comments that `Wi` is supposed to be the ISO week number, which makes the documentation on Ws and Wm incorrect.

**Comment by White-Tiger** [comment]
well... maybe it's wrong to say "ISO" for Ws and Wm... But otherwise, it's correct or isn't it?

**Comment by ygoe** [comment]
René, you have the more current fork I guess, so should/could I just deprecate this repo with a forward notice to your one? Or was there a problem with yours not having an issue tracker because it's a fork? In that case, I might just give you full access on this one so we can keep it all in one place.

**Comment by jerry1970** [comment]
Here is more info on different calculation methods:
http://en.wikipedia.org/wiki/Seven-day_week#Week_numbering

Most methods show the ISO-8601 way, which means 2015-02-23 is week 9.

The Wm and Ws and Wi formats are probably only used in US, Canada, Mexico, China, and Japan. I would definitely change the ISO part in the documentation and make it very clear those use the first full week for week 1.

Also, the Wm method isn't mentioned at all and seems an anomaly.

**Comment by White-Tiger** [comment]
@jerry1970 "Wi" **IS** ISO 8601 _(well should be from what I know, that's the reason why it exists)_
So what's your problem with that? _(and this statement is true for this and my T-Clock fork)_
_edit:_ to clarify things: Wi is supposed to be for Europe, Ws for North America and who knows who uses Wm and simple week number^^

@dg9ngf you asked about that a while ago :P Well.. we found out that it doesn't had an issue tracker because it's a fork... I just re-googled it and found out I could "simply" enable it xD _(so that's done)_
My other solution to delete my repo and recreate it without being a fork might have worked as well... but would have caused a loss of Stargazers and Watchers and other stuff :P
Anyway, issue tracker enabled, so do what you want to ;)

**Comment by jerry1970** [comment]
@White-Tiger, my problem was with the other formats. The documentation on Wm, Ws, and Ww stated ISO which was incorrect and there was no documentation on Wi.

**Comment by White-Tiger** [comment]
well... I don't really know the reasons why it said ISO on them... but it's probably because T-Clock is simply using [strftime](http://cplusplus.com/reference/ctime/strftime/), and that one is supposed to follow the ISO C Standard... so it probably was just likely for its formats to also follow ISO _(and since C is an ISO standard, ISO also said how %U and %W should be defined...)_

btw. thanks for reporting, I'll update my readme soon.

P.S. that the info about "Wi" were missing for you, was likely caused by the fact that dg9ngf's doc was updated but not his release... So you had the old docs :P My version had the new ones though.

**Comment by jerry1970** [comment]
Please note that the strftime function is not using ISO 8601 time by definition, but some of the formats are. On the link you gave you can see that %U and %W are not following ISO 8601, but %V is.

| specifier | replaced by |
| --- | --- |
| %U | Week number with the first Sunday as the first day of week one (00-53) |
| %V | ISO 8601 week number (00-53) |
| %W | Week number with the first Monday as the first day of week one (00-53) |

I have been confusing the different T-Clock versions before so I am not surprised I did that again. Most important thing is that Wi is following ISO 8601 and that is what I was looking for.

Thanks for taking the time to reply.
